### ISSUE TITLE
Add a functionality to add actual hours taken to complete a task.

### ISSUE THREAD

**Issue by purv2100** [aditicsalunkhe/Simplii-Group74-2023#16]
**Is your feature request related to a problem? Please describe.**
The time taken to complete a task can sometimes be overestimated or underestimated. Thus, in order to get good at managing task user should be able to compare the estimated time to complete the task with actual time it took. And that is why we are adding this functionality which enables user to provide the actual hours it took to complete any task.

**Describe the solution you'd like**
A field that takes actual hours when the user completes a task.

**Comment by WangWangIsDog** [comment]
This is not a significant improvement but could really improve user experience doing task track, please go and make this enhancement

**Comment by purv2100** [comment]
Yes, I will surely do that.
