### ISSUE TITLE
More analytics based on new features.

### ISSUE THREAD

**Issue by purv2100** [aditicsalunkhe/Simplii-Group74-2023#17]
**Is your feature request related to a problem? Please describe.**
This feature may solve the problem of user underestimating or overestimating the time it takes to complete a task by providing a visual comparison.

**Describe the solution you'd like**
A bar chart that compares actual hours with estimated hours for each task.

**Describe alternatives you've considered**

**Additional context**

**Comment by WangWangIsDog** [comment]
Visual is better than words when expressing data, but remember to pay attention to the size and color of the graph so not to disturb users` experience

**Comment by aditicsalunkhe** [comment]
@purv2100 Yes sure, I was working on that for a couple of days now. It is almost done. I'll be adding few more charts for better insights soon.

**Comment by aditicsalunkhe** [comment]
@WangWangIsDog Yes right, I'll make sure not to disturb or hamper the user experience with the visualization of charts. Currently I'm working on beautifying the charts. Thank you for the feedback! :)

**Comment by aditicsalunkhe** [comment]
Added new charts for better insights.
