### ISSUE TITLE
For the position of navigation bar, Make a transition from top bar design to left sidebar design; also add a website logo on upper part of sidebar

### ISSUE THREAD

**Issue by WangWangIsDog** [aditicsalunkhe/Simplii-Group74-2023#18]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. It`s a visual and user experience enhancement for the navigation bar of the website

**Describe the solution you'd like**
Reorganize the layout of web content and write related CSS files to style them.

**Describe alternatives you've considered**
None

**Additional context**
Also add a logo for "Simplii" instead of plain bold big font text

**Comment by aditicsalunkhe** [comment]
Yes, this sounds great to me. Please go ahead and commit any frontend related changes that you've made. We can then publish another release of the project.

**Comment by purv2100** [comment]
This will make our website look good.
