### ISSUE TITLE
Friend requests not showing up for the receiver 

### ISSUE THREAD

**Issue by mistryishan25** [aditicsalunkhe/Simplii-Group74-2023#21]
**Describe the bug**
The request is not available in the receiver's pending_requests
**To Reproduce**

1. Go to `Friends`
2. Click on `Add friends`
3. Press the toggle button to select the friend 

**Expected behavior**
The request should be visible in the `Pending requests` toggle card of the receiver.

**Comment by mistryishan25** [comment]
I just wanted to ask if anyone else is facing this issue or not.

**Comment by aditicsalunkhe** [comment]
Yes, even I'm facing the same issue. Apparently I'm sending requests to my friends but it doesn't show under their Pending Approval section. So, I'm not sure if Add Friends functionality is working fine or not.

**Comment by purv2100** [comment]
Yeah it is the same for me. Ishan would you take up this issue and solve the bug.

**Comment by mistryishan25** [comment]
Thanks for verifying the issue on your end. 

Sure! I think it might have something to do with the interaction elements(scripts.js) and the HTML contents. I might be able to fix it soon.
