### ISSUE TITLE
Discussion Forum

### ISSUE THREAD

**Issue by mistryishan25** [aditicsalunkhe/Simplii-Group74-2023#38]
**Is your feature request related to a problem? Please describe.**
Tasks are done more successfully when the members can easily communicate with each other. Also, the forum would facilitate the exchange of ideas!

**Describe the solution you'd like**
Have a separate tab in the menu for the discussions - `Forum` where users can create threads on almost any topic and people can comment on these threads.

**Comment by purv2100** [comment]
Would the discussion be general for all the users or would it be group of friends that are allowed or anything else?

**Comment by mistryishan25** [comment]
We can have them create a separate thread if they want. I think it would be nice to have just the common discussion forums for now.
