### ISSUE TITLE
Failing Test case - test_application.py

### ISSUE THREAD

**Issue by mistryishan25** [aditicsalunkhe/Simplii-Group74-2023#39]
**Test Case Description**
Brief description of the failing test case.

**Steps to Reproduce**
1. Go to the `/src` 
2. Execute the pytest command: `pytest test/test_application.py` 

**Environment**
Python Version: [e.g., 3.8]
Pytest Version: [e.g., 6.2.4]

**Actual Outcome**
`ImportModuleError` - The import was failing for the forms.

**Comment by aditicsalunkhe** [comment]
It might be a problem with missing dependency modules. Can you try to create your own version of requirements.txt? It will have all the dependencies that you actually used and might work. Let me try on my end as well.

**Comment by purv2100** [comment]
I can't see test directory.

**Comment by WangWangIsDog** [comment]
Maybe should check whether the related modules have correct name or have already been installed
