### ISSUE TITLE
Need to add setup.py for packaging and distribution of project.

### ISSUE THREAD

**Issue by aditicsalunkhe** [aditicsalunkhe/Simplii-Group74-2023#41]
**Is your feature request related to a problem? Please describe.**
The setup.py file is crucial for packaging and distributing Python projects. It contains essential metadata, dependencies, and structural information, enabling seamless installation and sharing of the code through tools like setup tools and pip. It automates the packaging process, ensures correct dependency management, and facilitates integration into broader ecosystems by allowing the declaration of entry points.

**Describe the solution you'd like**
Add setup.py file to the project before third release.

**Comment by purv2100** [comment]
So, we won't need installation steps now, right? Or we can keep them and add this as well as another method of setting up the repo.

**Comment by aditicsalunkhe** [comment]
Let's still keep it as some people might still want to install the application manually by following the installation steps.
