### ISSUE TITLE
Friend Requests - Sending invitations

### ISSUE THREAD

**Issue by mistryishan25** [aditicsalunkhe/Simplii-Group74-2023#6]
**Is your feature request related to a problem? Please describe.**
Systematically we are solving the problem of accountability using the Friend-related features.

**Describe the solution you'd like**
The user can send friend requests to anyone available in the "Friends" toggle tab of the `Friends` menu.

**Comment by aditicsalunkhe** [comment]
I think there's some bug in the Friends module. I'm not able to add friends.

**Comment by WangWangIsDog** [comment]
Same problem here, maybe we need firstly located where is the problem, frontend, backend or database?

**Comment by mistryishan25** [comment]
I think it is possibly an issue of the click elements not linking with the backend. I'll look into the `scripts.js` to check the click functions.
